"""
Prosperity 4 - Round 1 Trading Algorithm (OPTIMIZED)
=====================================================
Auto-generated by optimizer.py
Parameters optimized over 3 days of Round 1 price data.
"""

from datamodel import OrderDepth, TradingState, Order
from typing import List, Dict, Tuple, Any
import json


# == Optimized Constants =======================================================
POS_LIMIT = 80

# PEPPER (optimized)
PEPPER_SLOPE          = 0.00101 
PEPPER_BASE_ALPHA     = 0.13999999999999999
PEPPER_TAKE_MAX       = 8
PEPPER_BID_LEVELS     = 4
PEPPER_ASK_LEVELS     = 2
PEPPER_BID_QTY        = 25
PEPPER_ASK_QTY        = 6
PEPPER_SELL_THRESHOLD = 4
PEPPER_ASK_THRESHOLD  = 50
PEPPER_ASK_START      = 6


# == Helpers ===================================================================

def best_bid_ask(od: OrderDepth) -> Tuple:
    bb = max(od.buy_orders.keys())  if od.buy_orders  else None
    ba = min(od.sell_orders.keys()) if od.sell_orders else None
    return bb, ba

def mid_price(od: OrderDepth):
    bb, ba = best_bid_ask(od)
    if bb is not None and ba is not None:
        return (bb + ba) / 2.0
    if bb is not None:
        return float(bb)
    if ba is not None:
        return float(ba)
    return None


# == Logger (from 136338) ======================================================
class Logger:
    def __init__(self):
        self.logs = ""
        self.max_log_length = 3750

    def print(self, *objects: Any, sep=" ", end="\n"):
        self.logs += sep.join(map(str, objects)) + end

    def flush(self, state, orders, conversions, trader_data):
        from datamodel import ProsperityEncoder
        base = len(self._json([self._state(state, ""), self._orders(orders), conversions, "", ""]))
        lim  = (self.max_log_length - base) // 3
        print(self._json([
            self._state(state, self._cut(state.traderData, lim)),
            self._orders(orders), conversions,
            self._cut(trader_data, lim),
            self._cut(self.logs, lim),
        ]))
        self.logs = ""

    def _state(self, state, td):
        return [
            state.timestamp, td,
            [[l.symbol, l.product, l.denomination] for l in state.listings.values()],
            {s: [od.buy_orders, od.sell_orders] for s, od in state.order_depths.items()},
            self._trades(state.own_trades),
            self._trades(state.market_trades),
            state.position,
            self._obs(state.observations),
        ]

    def _trades(self, trades):
        return [[t.symbol, t.price, t.quantity, t.buyer, t.seller, t.timestamp]
                for arr in trades.values() for t in arr]

    def _obs(self, obs):
        co = {}
        for p, o in obs.conversionObservations.items():
            co[p] = [o.bidPrice, o.askPrice, o.transportFees,
                     o.exportTariff, o.importTariff, o.sugarPrice, o.sunlightIndex]
        return [obs.plainValueObservations, co]

    def _orders(self, orders):
        return [[o.symbol, o.price, o.quantity] for arr in orders.values() for o in arr]

    def _json(self, v):
        from datamodel import ProsperityEncoder
        return json.dumps(v, cls=ProsperityEncoder, separators=(",", ":"))

    def _cut(self, s, n):
        return s if len(s) <= n else s[:n - 3] + "..."

logger = Logger()


# == Trader ====================================================================
class Trader:

    LIMIT = {"ASH_COATED_OSMIUM": 80, "INTARIAN_PEPPER_ROOT": 80}

    # ACO parameters (optimized)
    ASH_FAIR           = 10000
    ASH_TAKE_VOL       = 16
    ASH_SOFT_LIMIT     = 45
    ASH_HARD_LIMIT     = 50
    ASH_DISREGARD_EDGE = 1
    ASH_JOIN_EDGE      = 2
    ASH_DEFAULT_EDGE   = 4

    def _clear(self, product, od, fair, limit, pos, bvol, svol):
        orders = []
        net = pos + bvol - svol
        if net > 0:
            for p in sorted(od.buy_orders.keys(), reverse=True):
                if p < round(fair) or net <= 0:
                    break
                vol = od.buy_orders[p]
                qty = min(vol, net, limit + pos - svol)
                if qty > 0:
                    orders.append(Order(product, p, -qty))
                    svol += qty
                    net -= qty
        elif net < 0:
            for p in sorted(od.sell_orders.keys()):
                if p > round(fair) or net >= 0:
                    break
                vol = -od.sell_orders[p]
                qty = min(vol, -net, limit - pos - bvol)
                if qty > 0:
                    orders.append(Order(product, p, qty))
                    bvol += qty
                    net += qty
        return orders, bvol, svol

    def _make(self, product, od, fair, limit, pos, bvol, svol,
              soft_lim, hard_lim, disregard_edge, join_edge, default_edge):
        orders = []
        asks_above = [p for p in od.sell_orders if p > fair + disregard_edge]
        bids_below = [p for p in od.buy_orders  if p < fair - disregard_edge]
        best_ask = min(asks_above) if asks_above else None
        best_bid = max(bids_below) if bids_below else None
        ask = round(fair + default_edge)
        if best_ask is not None:
            ask = best_ask if (best_ask - fair) <= join_edge else best_ask - 1
        bid = round(fair - default_edge)
        if best_bid is not None:
            bid = best_bid if (fair - best_bid) <= join_edge else best_bid + 1
        skew = 0
        if   abs(pos) > hard_lim: skew = 2
        elif abs(pos) > soft_lim: skew = 1
        if   pos > 0: ask -= skew
        elif pos < 0: bid += skew
        if bid >= ask:
            ask = bid + 1
        buy_qty  = limit - (pos + bvol)
        sell_qty = limit + (pos - svol)
        if buy_qty  > 0: orders.append(Order(product, round(bid),  buy_qty))
        if sell_qty > 0: orders.append(Order(product, round(ask), -sell_qty))
        return orders, bvol, svol

    def _run_ash(self, state: TradingState) -> list[Order]:
        product = "ASH_COATED_OSMIUM"
        if product not in state.order_depths: return []
        od    = state.order_depths[product]
        pos   = state.position.get(product, 0)
        fair  = self.ASH_FAIR
        limit = self.LIMIT[product]
        bvol  = svol = 0
        orders = []
        # -- Glitch sniper: take any absurdly cheap sells (bot errors) --
        if od.sell_orders:
            for px in sorted(od.sell_orders.keys()):
                if px >= fair - 20:
                    break
                vol = -od.sell_orders[px]
                qty = min(vol, limit - pos - bvol)
                if qty > 0:
                    orders.append(Order(product, px, qty))
                    bvol += qty

        # -- Glitch sniper: take any absurdly high buys (bot errors) --
        if od.buy_orders:
            for px in sorted(od.buy_orders.keys(), reverse=True):
                if px <= fair + 20:
                    break
                vol = od.buy_orders[px]
                qty = min(vol, limit + pos - svol)
                if qty > 0:
                    orders.append(Order(product, px, -qty))
                    svol += qty
        if od.sell_orders:
            best_ask = min(od.sell_orders)
            ask_vol  = -od.sell_orders[best_ask]
            if best_ask <= fair - 1 and ask_vol < self.ASH_TAKE_VOL:
                qty = min(ask_vol, limit - pos - bvol)
                if qty > 0:
                    orders.append(Order(product, best_ask, qty))
                    bvol += qty
        if od.buy_orders:
            best_bid = max(od.buy_orders)
            bid_vol  = od.buy_orders[best_bid]
            if best_bid >= fair + 1 and bid_vol < self.ASH_TAKE_VOL:
                qty = min(bid_vol, limit + pos - svol)
                if qty > 0:
                    orders.append(Order(product, best_bid, -qty))
                    svol += qty
        clear_o, bvol, svol = self._clear(product, od, fair, limit, pos, bvol, svol)
        orders += clear_o
        make_o, _, _ = self._make(product, od, fair, limit, pos, bvol, svol,
            self.ASH_SOFT_LIMIT, self.ASH_HARD_LIMIT,
            self.ASH_DISREGARD_EDGE, self.ASH_JOIN_EDGE, self.ASH_DEFAULT_EDGE)
        orders += make_o
        return orders

    def _run_pepper(self, state: TradingState, saved: Dict) -> List[Order]:
        orders = []
        od  = state.order_depths['INTARIAN_PEPPER_ROOT']
        pos = state.position.get('INTARIAN_PEPPER_ROOT', 0)
        ts  = state.timestamp
        mid = mid_price(od)
        if mid is not None:
            cur_base = mid - PEPPER_SLOPE * ts
            if 'pepper_base' not in saved:
                saved['pepper_base'] = cur_base
            else:
                saved['pepper_base'] = (
                    (1.0 - PEPPER_BASE_ALPHA) * saved['pepper_base']
                    + PEPPER_BASE_ALPHA * cur_base
                )
        base = saved.get('pepper_base', 10_000.0)
        fair = base + PEPPER_SLOPE * ts
        fair_r = round(fair)
        buy_cap  = POS_LIMIT - pos
        sell_cap = POS_LIMIT + pos
        # -- Glitch sniper: take any absurdly cheap sells (bot errors) --
        if od.sell_orders:
            for px in sorted(od.sell_orders.keys()):
                if px >= fair - 20:
                    break
                vol = -od.sell_orders[px]
                qty = min(vol, buy_cap)
                if qty > 0:
                    orders.append(Order('INTARIAN_PEPPER_ROOT', px, qty))
                    buy_cap -= qty
        logger.print(f"PEPPER: TS={ts}, Pos={pos}, Fair={fair:.2f}")
        for px in sorted(od.sell_orders.keys()):
            if px > fair + PEPPER_TAKE_MAX or buy_cap <= 0: break
            vol = -od.sell_orders[px]
            qty = min(vol, buy_cap)
            orders.append(Order('INTARIAN_PEPPER_ROOT', px, qty))
            buy_cap -= qty
        for px in sorted(od.buy_orders.keys(), reverse=True):
            if px <= fair + PEPPER_SELL_THRESHOLD or sell_cap <= 0: break
            vol = od.buy_orders[px]
            qty = min(vol, sell_cap)
            orders.append(Order('INTARIAN_PEPPER_ROOT', px, -qty))
            sell_cap -= qty
        for level in range(1, PEPPER_BID_LEVELS + 1):
            if buy_cap <= 0: break
            qty = min(PEPPER_BID_QTY, buy_cap)
            orders.append(Order('INTARIAN_PEPPER_ROOT', fair_r - level, qty))
            buy_cap -= qty
        if pos > PEPPER_ASK_THRESHOLD and sell_cap > 0:
            for level in range(PEPPER_ASK_START, PEPPER_ASK_START + PEPPER_ASK_LEVELS):
                if sell_cap <= 0: break
                qty = min(PEPPER_ASK_QTY, sell_cap)
                orders.append(Order('INTARIAN_PEPPER_ROOT', fair_r + level, -qty))
                sell_cap -= qty
        return orders

    def run(self, state: TradingState):
        saved = {}
        if state.traderData:
            try: saved = json.loads(state.traderData)
            except Exception: saved = {}
        result = {}
        conversions = 0
        ash_o = self._run_ash(state)
        if ash_o: result["ASH_COATED_OSMIUM"] = ash_o
        if 'INTARIAN_PEPPER_ROOT' in state.order_depths:
            ipr_o = self._run_pepper(state, saved)
            if ipr_o: result["INTARIAN_PEPPER_ROOT"] = ipr_o
        trader_data = json.dumps(saved)
        logger.flush(state, result, conversions, trader_data)
        return result, conversions, trader_data