//! VEV_6500 — Round 3 product.
//!
//! Auto-generated by `tmp/generate_r3_asset_rs.py` from
//! `calibration/vev_6500/params.json`. Edit the params file and re-run the
//! generator instead of editing this file by hand.
//!
//! Calibration: see `calibration/vev_6500/calibration.md`.

use crate::asset::{
    AssetSim, Book, FlagKind, FlagSpec, load_replay_fv_path, parse_path, sample_standard_normal,
};
use anyhow::Result;
use rand::distributions::{Distribution, WeightedIndex};
use rand::Rng;
use rand_chacha::ChaCha8Rng;
use std::collections::HashMap;

pub const SYMBOL: &str = "VEV_6500";

const POSITION_LIMIT: i32 = 300;
const BASE_TRADE_PROB: f64 = 0.09309309309309309;
const SECOND_TRADE_PROB: f64 = 0.017921146953405017;
const ELASTIC_TRADE_PROB: f64 = 0.018618618618618618;
const BUY_PROB: f64 = 0.5;

pub struct Vev6500 {
    replay_fv: Option<Vec<f64>>,
}

pub fn flag_specs() -> Vec<FlagSpec> {
    vec![FlagSpec {
        name: "replay-fv",
        kind: FlagKind::Path,
        default: None,
        help: "Replay observed FV (JSON: flat [f64] or object with 'vev_6500' key)",
    }]
}

pub fn build(flags: &HashMap<String, String>) -> Result<Box<dyn AssetSim>> {
    let replay_fv = match flags.get("replay-fv") {
        Some(raw) => {
            let path = parse_path("vev-6500-replay-fv", raw)?;
            Some(load_replay_fv_path(&path, "vev_6500")?)
        }
        None => None,
    };
    Ok(Box::new(Vev6500 { replay_fv }))
}

/// Banker's rounding (round half to even) — matches the calibration kernel
/// and the Rust formula_search; differs from f64::round which rounds half away from 0.
fn banker_round(x: f64) -> i64 {
    let f = x.floor();
    let frac = x - f;
    if frac > 0.5 { (f as i64) + 1 }
    else if frac < 0.5 { f as i64 }
    else {
        let fi = f as i64;
        if fi % 2 == 0 { fi } else { fi + 1 }
    }
}

fn sample_weighted(values: &[i32], weights: &[u32], rng: &mut ChaCha8Rng) -> i32 {
    let chooser = WeightedIndex::new(weights).expect("valid weights");
    values[chooser.sample(rng)]
}

impl AssetSim for Vev6500 {
    fn symbol(&self) -> &str {
        SYMBOL
    }

    fn position_limit(&self) -> i32 {
        POSITION_LIMIT
    }

    fn simulate_fv(
        &self,
        day_index: usize,
        ticks: usize,
        rng: &mut ChaCha8Rng,
    ) -> Result<Vec<f64>> {
        if let Some(observed) = &self.replay_fv {
            let mut out = Vec::with_capacity(ticks);
            for i in 0..ticks {
                out.push(observed[i.min(observed.len().saturating_sub(1))]);
            }
            return Ok(out);
        }
        let _ = day_index;
        let mean: f64 = 0.0;
        let sigma: f64 = 0.0;
        let mut values = Vec::with_capacity(ticks);
        for _ in 0..ticks {
            values.push(mean + sigma * sample_standard_normal(rng));
        }
        Ok(values)
    }

    fn make_book(&self, fair: f64, rng: &mut ChaCha8Rng) -> Book {
        let mut bids: Vec<(i32, i32)> = Vec::new();
        let mut asks: Vec<(i32, i32)> = Vec::new();
        // Bot 1: bid_rate=0.999 ask_rate=0.999  sides_tied=True
        let v1 = sample_weighted(&[7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], &[1, 23, 58, 77, 89, 138, 129, 113, 121, 117, 63, 41, 25, 1, 1, 1, 1], rng);
        if rng.gen_bool(0.999) { bids.push(((fair + 0.25).ceil() as i32 - 1, v1)); }
        if rng.gen_bool(0.999) { asks.push(((fair - 0.75).floor() as i32 + 2, v1)); }
        bids.sort_by(|a, b| b.0.cmp(&a.0));
        asks.sort_by(|a, b| a.0.cmp(&b.0));
        Book { bids, asks }
    }

    fn base_trade_prob(&self) -> f64 {
        BASE_TRADE_PROB
    }

    fn second_trade_prob(&self) -> f64 {
        SECOND_TRADE_PROB
    }

    fn elastic_trade_prob(&self) -> f64 {
        ELASTIC_TRADE_PROB
    }

    fn buy_prob(&self) -> f64 {
        BUY_PROB
    }

    fn sample_trade_qty(
        &self,
        market_buy: bool,
        volume_limit: i32,
        rng: &mut ChaCha8Rng,
    ) -> i32 {
        let _ = market_buy;
        let values: &[i32] = &[2, 3, 4, 5];
        let weights: &[u32] = &[76, 56, 78, 74];
        let filtered: Vec<(i32, u32)> = values.iter().zip(weights.iter())
            .filter(|(v, _)| **v <= volume_limit).map(|(v, w)| (*v, *w)).collect();
        if filtered.is_empty() { return volume_limit.max(1); }
        let vals: Vec<i32> = filtered.iter().map(|(v, _)| *v).collect();
        let ws: Vec<u32> = filtered.iter().map(|(_, w)| *w).collect();
        let chooser = WeightedIndex::new(ws).expect("valid trade weights");
        vals[chooser.sample(rng)]
    }
}
