//! VEV_5100 — Round 3 product.
//!
//! Auto-generated by `tmp/generate_r3_asset_rs.py` from
//! `calibration/vev_5100/params.json`. Edit the params file and re-run the
//! generator instead of editing this file by hand.
//!
//! Calibration: see `calibration/vev_5100/calibration.md`.

use crate::asset::{
    AssetSim, Book, FlagKind, FlagSpec, load_replay_fv_path, parse_path, sample_standard_normal,
};
use anyhow::Result;
use rand::distributions::{Distribution, WeightedIndex};
use rand::Rng;
use rand_chacha::ChaCha8Rng;
use std::collections::HashMap;

pub const SYMBOL: &str = "VEV_5100";

const POSITION_LIMIT: i32 = 80;
const BASE_TRADE_PROB: f64 = 0.000333667000333667;
const SECOND_TRADE_PROB: f64 = 0.0;
const ELASTIC_TRADE_PROB: f64 = 6.67334000667334e-05;
const BUY_PROB: f64 = 0.5;

pub struct Vev5100 {
    replay_fv: Option<Vec<f64>>,
}

pub fn flag_specs() -> Vec<FlagSpec> {
    vec![FlagSpec {
        name: "replay-fv",
        kind: FlagKind::Path,
        default: None,
        help: "Replay observed FV (JSON: flat [f64] or object with 'vev_5100' key)",
    }]
}

pub fn build(flags: &HashMap<String, String>) -> Result<Box<dyn AssetSim>> {
    let replay_fv = match flags.get("replay-fv") {
        Some(raw) => {
            let path = parse_path("vev-5100-replay-fv", raw)?;
            Some(load_replay_fv_path(&path, "vev_5100")?)
        }
        None => None,
    };
    Ok(Box::new(Vev5100 { replay_fv }))
}

/// Banker's rounding (round half to even) — matches the calibration kernel
/// and the Rust formula_search; differs from f64::round which rounds half away from 0.
fn banker_round(x: f64) -> i64 {
    let f = x.floor();
    let frac = x - f;
    if frac > 0.5 { (f as i64) + 1 }
    else if frac < 0.5 { f as i64 }
    else {
        let fi = f as i64;
        if fi % 2 == 0 { fi } else { fi + 1 }
    }
}

fn sample_weighted(values: &[i32], weights: &[u32], rng: &mut ChaCha8Rng) -> i32 {
    let chooser = WeightedIndex::new(weights).expect("valid weights");
    values[chooser.sample(rng)]
}

impl AssetSim for Vev5100 {
    fn symbol(&self) -> &str {
        SYMBOL
    }

    fn position_limit(&self) -> i32 {
        POSITION_LIMIT
    }

    fn simulate_fv(
        &self,
        day_index: usize,
        ticks: usize,
        rng: &mut ChaCha8Rng,
    ) -> Result<Vec<f64>> {
        if let Some(observed) = &self.replay_fv {
            let mut out = Vec::with_capacity(ticks);
            for i in 0..ticks {
                out.push(observed[i.min(observed.len().saturating_sub(1))]);
            }
            return Ok(out);
        }
        let _ = day_index;
        let sigma: f64 = 0.8167258858388822;
        let drift: f64 = 0.0;
        let mean: f64 = 174.79315318431225;
        let mut values = Vec::with_capacity(ticks);
        if ticks == 0 { return Ok(values); }
        // Start at mean for day 0; otherwise we'd want a continuous chain across days,
        // but R3 calibration is per-day-2 hold-1, so each day starts independently.
        values.push(mean);
        for _ in 1..ticks {
            let step = drift + sigma * sample_standard_normal(rng);
            values.push(values[values.len() - 1] + step);
        }
        Ok(values)
    }

    fn make_book(&self, fair: f64, rng: &mut ChaCha8Rng) -> Book {
        let mut bids: Vec<(i32, i32)> = Vec::new();
        let mut asks: Vec<(i32, i32)> = Vec::new();
        // Bot 1: bid_rate=0.689 ask_rate=0.703  sides_tied=False
        let v1_bid = sample_weighted(&[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36], &[60, 55, 57, 58, 49, 55, 44, 62, 57, 58, 71, 68, 78, 26, 22, 36, 19, 38, 25, 16, 19, 15, 4, 6, 3], rng);
        let v1_ask = sample_weighted(&[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36], &[60, 55, 57, 58, 49, 55, 44, 62, 57, 58, 71, 68, 78, 26, 22, 36, 19, 38, 25, 16, 19, 15, 4, 6, 3], rng);
        if rng.gen_bool(0.689) { bids.push(((fair - 0.5).floor() as i32 - 2, v1_bid)); }
        if rng.gen_bool(0.703) { asks.push(((fair - 0.5).floor() as i32 + 4, v1_ask)); }
        // Bot 2: bid_rate=0.746 ask_rate=0.763  sides_tied=False
        let v2_bid = sample_weighted(&[6, 7, 8, 9, 10, 11, 12, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36], &[80, 70, 88, 92, 68, 92, 92, 4, 9, 13, 28, 28, 24, 19, 36, 28, 42, 27, 25, 23, 40, 25, 17, 7, 13, 5], rng);
        let v2_ask = sample_weighted(&[6, 7, 8, 9, 10, 11, 12, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36], &[80, 70, 88, 92, 68, 92, 92, 4, 9, 13, 28, 28, 24, 19, 36, 28, 42, 27, 25, 23, 40, 25, 17, 7, 13, 5], rng);
        if rng.gen_bool(0.746) { bids.push(((fair - 0.5).floor() as i32 - 1, v2_bid)); }
        if rng.gen_bool(0.763) { asks.push(((fair - 0.5).floor() as i32 + 3, v2_ask)); }
        bids.sort_by(|a, b| b.0.cmp(&a.0));
        asks.sort_by(|a, b| a.0.cmp(&b.0));
        Book { bids, asks }
    }

    fn base_trade_prob(&self) -> f64 {
        BASE_TRADE_PROB
    }

    fn second_trade_prob(&self) -> f64 {
        SECOND_TRADE_PROB
    }

    fn elastic_trade_prob(&self) -> f64 {
        ELASTIC_TRADE_PROB
    }

    fn buy_prob(&self) -> f64 {
        BUY_PROB
    }

    fn sample_trade_qty(
        &self,
        market_buy: bool,
        volume_limit: i32,
        rng: &mut ChaCha8Rng,
    ) -> i32 {
        let _ = market_buy;
        let values: &[i32] = &[1];
        let weights: &[u32] = &[1];
        let filtered: Vec<(i32, u32)> = values.iter().zip(weights.iter())
            .filter(|(v, _)| **v <= volume_limit).map(|(v, w)| (*v, *w)).collect();
        if filtered.is_empty() { return volume_limit.max(1); }
        let vals: Vec<i32> = filtered.iter().map(|(v, _)| *v).collect();
        let ws: Vec<u32> = filtered.iter().map(|(_, w)| *w).collect();
        let chooser = WeightedIndex::new(ws).expect("valid trade weights");
        vals[chooser.sample(rng)]
    }
}
