// Stage 8 — assemble a params.json from the upstream stage results.
//
// Produces the canonical params shape defined in calibration/params_schema.md.
// The frontend does NOT write to disk — it POSTs to the server endpoint
// POST /__prosperity4mcbt__/calibration/params?asset=X, which persists to
// calibration/<asset_lower>/params.json.

import { BotSpec, CalibrationParams, FvProcessType } from '../types';
import { layersToBotSpecs, Stage2Result } from './formula_discovery';
import { FvFitResult } from './fv_process';
import { Stage1Result } from './layer_detection';
import { Stage4Result } from './presence_model';
import { Stage3Result } from './volume_model';

export function assembleParams(
  asset: string,
  fv: FvFitResult | null,
  s1: Stage1Result | null,
  s2: Stage2Result | null,
  s3: Stage3Result | null,
  s4: Stage4Result | null,
): CalibrationParams {
  if (!fv || !s1 || !s2) {
    throw new Error('Stage 8 requires at least Stages 0-2 to have run');
  }

  // ── FV process block ──
  let fvParams: Record<string, number> = {
    quantization: fv.diagnostics.quantization.value,
  };
  const fvType: FvProcessType = fv.pickedType;
  if (fvType === 'random_walk') {
    fvParams.drift = 0;
    fvParams.sigma = fv.diagnostics.stdStep;
    fvParams.mean  = fv.diagnostics.meanFv;
  } else if (fvType === 'linear_drift') {
    fvParams.drift = fv.diagnostics.linearFit.beta;
    fvParams.mean  = fv.diagnostics.linearFit.alpha;
    fvParams.sigma = fv.diagnostics.linearFit.residualStd;
  } else if (fvType === 'ar1') {
    fvParams.ar1_coef = fv.diagnostics.deltaAc1;
    fvParams.drift = fv.diagnostics.meanStep;
    fvParams.sigma = fv.diagnostics.stdStep;
  } else {
    fvParams.mean = fv.diagnostics.meanFv;
    fvParams.sigma = fv.diagnostics.stdFv;
  }

  // ── Bot specs (start from Stage 2 formulas, enrich with Stage 3/4 if present) ──
  const bots: BotSpec[] = layersToBotSpecs(s1.layers, s2);
  if (s3) {
    for (const model of s3.layers) {
      const b = bots.find(x => x.id === model.layer_id);
      if (!b) continue;
      b.volume = {
        distribution: 'uniform',
        low: Math.min(model.bid.min, model.ask.min),
        high: Math.max(model.bid.max, model.ask.max),
        sides_tied: model.sides_tied_rate > 0.95,
      };
      b.diagnostics = {
        ...(b.diagnostics ?? {}),
        bid_vol_uniform_p: model.bid.uniform.p_value,
        ask_vol_uniform_p: model.ask.uniform.p_value,
        sides_tied_rate: model.sides_tied_rate,
      };
    }
  }
  if (s4) {
    for (const model of s4.layers) {
      const b = bots.find(x => x.id === model.layer_id);
      if (!b) continue;
      b.presence = {
        rate: (model.bid.rate + model.ask.rate) / 2,
        iid: model.bid.ljung.p_value > 0.05 && model.ask.ljung.p_value > 0.05,
        bid_ask_independent: model.bid_ask_indep.p_value > 0.05,
      };
      b.diagnostics = {
        ...(b.diagnostics ?? {}),
        bid_presence_rate: model.bid.rate,
        ask_presence_rate: model.ask.rate,
        bid_ask_indep_p: model.bid_ask_indep.p_value,
      };
    }
  }

  return {
    asset,
    position_limit: 80,  // all current assets use 80; Stage 8 doesn't try to infer it
    fv_process: {
      type: fvType,
      params: fvParams,
      diagnostics: {
        n_ticks: fv.diagnostics.nTicks,
        residual_ljung_p: fv.diagnostics.residualLjung.p,
        residual_skew_z:  fv.diagnostics.skewZ,
        residual_kurt_z:  fv.diagnostics.kurtZ,
      },
    },
    bots,
    metadata: {
      calibrated_from: 'discovery pipeline (frontend, Stages 0-4)',
      pipeline_version: '1.0.0',
      timestamp: new Date().toISOString(),
      notes: 'Auto-generated by the Calibration tab. Review formulas vs. observed match rates before shipping.',
    },
  };
}
