"""Bake the factor model + per-asset σ + per-asset h into a Python module
that the trader can import (or copy-paste from)."""
from __future__ import annotations
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
LOAD = json.loads((Path(__file__).with_name("factor_loadings.json")).read_text())
SCEN = json.loads((REPO / "calibration" / "r5" / "scenario_params.json").read_text())

ASSETS = LOAD["assets"]                  # 50, fixed order
N = len(ASSETS)
K = 4                                     # number of stable factors

# CORR-PCA gives unit-variance components. Convert to dollar loadings:
# diff_i ≈ Σ_k L_dollar[k,i] * f_k  with f_k unit-variance dollar increment per √λ_k.
# For neutralization purposes we want exposure(asset i, factor k) in unit-position terms,
# i.e. how many $ of factor exposure per +1 unit of asset i. That is:
#   B[k,i] = sigma_i * V_corr[i,k]    (σ_i in raw-diff units)
# When neutralizing position vector p, factor exposure = B @ p  (in $/tick variance contribution).
sigma_i = LOAD["per_asset_std_diff"]      # dict: sym -> std of mid diffs
sigma_vec = [float(sigma_i[s]) for s in ASSETS]

# CORR-PCA loadings — each row (1×50) is a unit eigenvector of the correlation matrix
V_corr = LOAD["corr_pca"]["loadings_pc1_pc10"]  # list of 10 lists of 50

# Build B: K × N exposure matrix in dollar/unit-position terms
B = [[float(sigma_vec[i] * V_corr[k][i]) for i in range(N)] for k in range(K)]

# Mid-price levels for dollar-neutral row (use day-2 starts as a reference)
day_starts = SCEN["day_starts"]
ref_mid = [float(day_starts["2"][s]) for s in ASSETS]  # all 10000 in current calibration

print("// auto-generated by analysis/round5/bake_factor_constants.py")
print(f"ASSETS = (")
for s in ASSETS:
    print(f"    {s!r},")
print(")")
print(f"\nN_ASSETS = {N}")
print(f"\nK_FACTORS = {K}\n")

print("# per-asset 1-tick mid diff std (raw diffs, days 2-4 historical)")
print("SIGMA = {")
for s, sig in zip(ASSETS, sigma_vec):
    print(f"    {s!r}: {sig:.4f},")
print("}")

print("\n# Factor exposure matrix B[k][i] = sigma_i * V_corr[k, i]")
print("# Factor labels: PC1=snackpack_triplet, PC2=pebble_basket, PC3=choc_van_pair, PC4=mixed_broad")
print("FACTOR_LABELS = ('triplet', 'pebble_basket', 'choc_van_pair', 'mixed')")
print("FACTOR_EXPOSURE = (  # K rows × N cols")
for k in range(K):
    row = ", ".join(f"{B[k][i]:+.4f}" for i in range(N))
    print(f"    ({row}),")
print(")")

# Save also as JSON for the trader to embed
out = {
    "assets": ASSETS,
    "n_factors": K,
    "factor_labels": ["triplet", "pebble_basket", "choc_van_pair", "mixed"],
    "sigma_per_asset": dict(zip(ASSETS, sigma_vec)),
    "exposure_matrix": B,                 # K × N, in $/unit-position
    "ref_mid": dict(zip(ASSETS, ref_mid)),
}
out_path = Path(__file__).with_name("factor_constants.json")
out_path.write_text(json.dumps(out, indent=2))
print(f"\n# wrote {out_path}", file=__import__('sys').stderr)
